project:
  type: website
  output-dir: docs
website:
  title: "얼레벌레 공부벌레"
  page-footer:
    border: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - Memo.qmd
      - Baekjoon.qmd
      - Data_ToolBox.qmd
format:
  html:
    theme: cosmo
    css: styles.css



