project:
  type: website

website:
  title: "얼레벌레 공부벌레"
  navbar:
    left:
      - text : 데이터 시각화
        href : 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hyeonji07
    
format:
  html:
    theme: cosmo
    css: styles.css



